### ISSUE TITLE
Game crashes when I load it up with the mod.

### ISSUE THREAD

**Issue by Haiduc74** [terrapass/ck3-mod-custom-form-of-address#7]
When I load up the game with the mod turned on the game crashes. It dosen't seem to be a compability issue as I tried loading the mod alone but it still crashed. I am on version 1.8.0 and using the latest version of the mod.

**Comment by terrapass** [comment]
Did you download the mod from Steam Workshop, PDX Mods or some other source?
The current version of the mod is `0.3.7`, which was tested with game version `1.8.0`. See if your descriptor file lists it as such.

If you're indeed using the latest version, could you please zip-up and attach the folder, corresponding to your crash with no other mods running, from your `Documents\Paradox Interactive\Crusader Kings III\crashes` directory?

**Comment by terrapass** [comment]
Just looked at Paradox Mods page and realized it had an outdated version of the mod.
I've uploaded a fresh version there, so if you installed the mod from Paradox Mods, make sure you download the update.

**Comment by Haiduc74** [comment]
That was the problem, did what you sugested, launched the game and everything worked just fine. Thank you very much for the help.
